services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: game
      LANG: C.UTF-8
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD:
      DB_NAME: game
      SESSION_KEY: 'secret cat'
    depends_on:
      - db

volumes:
  mysql_data:
